# Generated by Django 3.2.5 on 2024-11-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('id_document', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор удостоверения личности')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('workplace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы')),
                ('photo', models.ImageField(upload_to='client_photos/', verbose_name='Фотография')),
            ],
        ),
    ]
